GET http://localhost:5000/notes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzQ4MTY3MTQ3LCJleHAiOjE3NDgxNzA3NDd9.Y_0u8PEx8GdgLqUJL5uTBR_cvzsEyieJ1eYHAuZ9Cb0

###

POST http://localhost:5000/add-note 
Content-Type: application/json

{
    "nama": "tes",
    "isi": "aku capek mau bobok plis mas nanti masih kelas ekonomi, tapi ya gimana lagi"
}

### 

PUT http://localhost:5000/edit-note/1
Content-Type: application/json

{
    "nama": "peler",
    "isi": "tapi ya gimana lagi"
}

###

DELETE http://localhost:5000/delete-note/17

###


POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "admin4",
  "password": "123456"
}

####

POST https://notes-be148-870764645625.us-central1.run.app/login
Content-Type: application/json

{
  "username": "admin4",
  "password": "123456"
}

###

GET http://localhost:5000/users

